name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: 
      - main
jobs:
  install-package: 
    name: Cài đặt các gói cần thiết
    steps:
      - run: echo "Đang cài đặt các gói"
      - run: echo "Packages installed"
  build-ios: 
    name: Build ipa ios
    needs: install-package
    steps:
      - run: echo "Building ios"
      - run: echo "Ios completed"
  build-android: 
    name: Build apk android
    needs: install-package
    steps:
      - run: echo "Building android"
      - run: echo "Android completed"
  done:
    name: Đã build xong
    needs: [build-ios, build-android]
    steps:
      - run: echo "Ios and Android completed"